### ISSUE TITLE
Solstice 2.0

### ISSUE THREAD

**Issue by baabaablackgoat** [MGF1998/SolsticeBot#79]
**A complete overhaul of Solstice.**
Because of some commands being utterly broken, I would like to rewrite Solstice from the ground up, in the hopes to make everything more stable, modularisable etc.

**These commands/features will be ported:**
- [x] Audio Playing Feature (YTDL and local files.)
- [x] Command help
- [x] Access Values (Is the user permitted to do this?)
- [ ] User Management (Ban, Kick, Roleban.)
- [ ] Bot Bans (Restrict a user from using the bot.)
- [ ] User Information (This command will be enhanced with all kinds of info.)
- [ ] Chat Management (purge)
- [x] Remind me (Ping a user after a specified time.)
- [x] Voting system (including a voting system for the music queue.)
- [ ] Mod Log (The NSA-Staff is watching you)
- [x] And of course the "joke" commands. (Bang, Cock, Fix, Fuck, Hentie, Hugs, Memes)

**These things will be new:**
- [x] giveme (Allow users - under certain circumstances - to assign themselves roles.)
- [x] Playing feature will support youtube search.
- [ ] If possible, Playing feature will also support other platforms like SoundCloud.
- [x] Allow usage of Discord native permissions instead of Access Values.
- [ ] `now` - accurate representation of timezones around the world. #75
- [ ] Slowmode/Lockdown - Temporairly lock a text channel to staff talking only. #51 
- [ ] (Maybe) automatic spam detection, and taking care of it #47
- [ ] A discord based version of [Spyfall from Alexandr Ushan](https://github.com/evanbrumley/spyfall)
And more to come, whatever pops into my mind.
